### ISSUE TITLE
Consider dropping protoc-gen-grpc-web in favor of protoc-gen-ts

### ISSUE THREAD

**Issue by thesayyn** [paperclip-ui/paperclip#133]
gRPC Web support has been added to protoc-gen-ts recently.  See https://github.com/thesayyn/protoc-gen-ts/releases/tag/0.8.6-rc1

**Comment by crcn** [comment]
One step ahead of you! https://github.com/paperclip-ui/paperclip/blob/master/libs/proto/package.json#L22
